#!/usr/bin/env Rscript

# Generate the TypeScript geometry module used by VennPlus from the authoritative
# five-set data bundled with Adrian Dusa's `venn` package. The generated file is
# deterministic and preserves the original geometry to four decimal places in
# the normalized SVG coordinate system.

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 2) {
  stop("Usage: generate-venn5-reference.R <venn/R/sysdata.rda> <output.ts>")
}

source_data <- normalizePath(args[[1]], mustWork = TRUE)
output_file <- args[[2]]
load(source_data)

normalize_x <- function(value) (value - 500) / 125
normalize_y <- function(value) (500 - value) / 125
number <- function(value) {
  rendered <- sprintf("%.4f", value)
  rendered <- sub("0+$", "", rendered)
  rendered <- sub("\\.$", "", rendered)
  if (identical(rendered, "-0")) "0" else rendered
}

mask_from_label <- function(label) {
  digits <- as.integer(strsplit(as.character(label), "")[[1]])
  sum(2 ^ (digits - 1))
}

set_rows <- subset(sets, s == 5 & v == 0)
contours <- lapply(1:5, function(set_index) {
  rows <- subset(set_rows, n == set_index & complete.cases(set_rows))
  if (
    nrow(rows) > 1 &&
    identical(rows$x[[1]], rows$x[[nrow(rows)]]) &&
    identical(rows$y[[1]], rows$y[[nrow(rows)]])
  ) {
    rows <- rows[-nrow(rows), ]
  }
  rows
})

intersection_rows <- subset(icoords, s == 5 & v == 0 & l != 0)
set_label_rows <- subset(scoords, s == 5 & v == 0)

lines <- c(
  "// Generated by scripts/generate-venn5-reference.R.",
  "// Source: Adrian Dusa (2026), venn 1.13, built-in five-set geometry.",
  "// Copyright (c) 2016-2024 Adrian Dusa. See THIRD_PARTY_NOTICES.md.",
  "// Do not edit this file by hand; regenerate it from venn/R/sysdata.rda.",
  "",
  "import type { LabelPoint, ShapeGeometry } from '../types';",
  "",
  "export const VENN5_REFERENCE_VIEW_BOX: [number, number, number, number] = [-4, -4, 8, 8];",
  "",
  "export const VENN5_REFERENCE_SHAPES: ShapeGeometry[] = ["
)

for (rows in contours) {
  point_lines <- vapply(seq_len(nrow(rows)), function(index) {
    paste0(
      "      { x: ", number(normalize_x(rows$x[[index]])),
      ", y: ", number(normalize_y(rows$y[[index]])), " },"
    )
  }, character(1))
  lines <- c(lines, "  {", "    kind: 'contour',", "    points: [", point_lines, "    ],", "  },")
}

lines <- c(lines, "];", "", "export const VENN5_REFERENCE_REGION_LABELS = new Map<number, LabelPoint>([")
for (index in seq_len(nrow(intersection_rows))) {
  row <- intersection_rows[index, ]
  lines <- c(
    lines,
    paste0(
      "  [", mask_from_label(row$l), ", { x: ", number(normalize_x(row$x)),
      ", y: ", number(normalize_y(row$y)), " }],"
    )
  )
}

lines <- c(lines, "]);", "", "export const VENN5_REFERENCE_SET_LABELS: LabelPoint[] = [")
for (index in seq_len(nrow(set_label_rows))) {
  row <- set_label_rows[index, ]
  lines <- c(
    lines,
    paste0(
      "  { x: ", number(normalize_x(row$x)),
      ", y: ", number(normalize_y(row$y)), " },"
    )
  )
}

lines <- c(lines, "];", "")
dir.create(dirname(output_file), recursive = TRUE, showWarnings = FALSE)
writeLines(lines, output_file, useBytes = TRUE)
